version: '3.8'
services:
  php:
    build: .
    container_name: 'challenge-php'
    volumes:
      - ./src:/var/www/html
    environment:
      - PHP_EXTENSION_BCMATH=1
      - PHP_EXTENSION_XDEBUG=1
      - PHP_INI_XDEBUG__REMOTE_AUTOSTART=1
      - PHP_EXTENSION_INTL=1
      - PHP_INI_XDEBUG__REMOTE_PORT=10000
      - PHP_INI_SESSION__SAVE_PATH=/var/lib/php/session
    networks:
      - challenge-network
    ports:
      - '10000:10000'
    logging:
      options:
        max-size: '10m'
        max-file: '3'
  nginx:
    image: nginx:1.21.6-alpine
    container_name: 'challenge-nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html/
    networks:
      - challenge-network
    ports:
      - '8089:80'
    logging:
      options:
        max-size: '10m'
        max-file: '3'
  db:
    image: mysql:8.0.28
    container_name: 'challenge-db'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - app_data:/var/lib/mysql
    environment:
      MYSQL_USER: app # Just a default pw
      MYSQL_PASSWORD: password # Just a default pw
      MYSQL_ROOT_PASSWORD: password # Just a default pw
    networks:
      - challenge-network
    ports:
      - '8306:3306'
    logging:
      options:
        max-size: '10m'
        max-file: '3'
volumes:
  app_data:
networks:
  challenge-network:
    driver: bridge
